# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: $title-placeholder$
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for $subject-placeholder$, created by $author-placeholder$.

author: $author$
subject: $subject$
website: $website$
email: $email$
imprint: $imprint$
support: $support$

baseurl: "/mov" # the subpath of your site, e.g. /blog
url: " https://hw-sn.github.io." # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: #jekyllrb
github_username:  $author$

# Build settings
theme: minima
# plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
 - .sass-cache/
 - .jekyll-cache/
 - gemfiles/
 - Gemfile
 - Gemfile.lock
 - node_modules/
 - vendor/bundle/
 - vendor/cache/
 - vendor/gems/
 - vendor/ruby/
includes:
- docs
- img

# Collections === OLD APPROACH ===
# The collections_dir specifies where the source files for publishing are;
# When specified, _posts and _drafts need to be moved into the specified dir;
# Do not start the dir with an underscore
# collections_dir: docs
# The collection folders need to be in the collections_dir;
# They must start with an underscore; Note that the collection folder must be
# directly in the collections_dir, deeper hierarchy definitions are not possible
# Set output: true to ensure that the collection is published
# For the permalink: set the output file structure, but note when you use :path,
# set :output_ext so that the file extension is appended properly
#collections:
#  fruits:
#    output: true
#    permalink: /docs/en/fruits/:path:output_ext
#  tests:
#    output: true
#    permalink: /docs/en/tests/:path:output_ext
#
defaults:
  -
    scope:
      path: "docs"
    values:
      layout: "page"
      isDoc: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      no_breadcrumbs: true

# Permalink style for files in _posts
permalink: pretty


# Post settings
# content above the excerpt separator is accessed as a snippet via the
# {{ page.excerpt }} or {{ post.excerpt }} variables
excerpt_separator: <!--more-->


# Filter used to process markdown.
# Note that kramdown differs from github-flavored markdown in some subtle ways
markdown: kramdown
