# Site settings
title: $title-placeholder$
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for $subject-placeholder$, created by $author-placeholder$.

author: $author$
subject: $subject$
website: $website$
email: $email$
imprint: $imprint$
support: $support$

baseurl: "/mov" # the subpath of your site, e.g. /blog
url: "https://hw-sn.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
